### AnyKernel3 - Xiaomi Cepheus
## Kernel installer configuration
## Based on the AnyKernel3 framework by osm0sis @ xda-developers

### AnyKernel setup
properties() { '
kernel.string=InfiniR Kernel for Xiaomi Cepheus
do.devicecheck=1
do.modules=0
do.systemless=0
do.cleanup=1
do.cleanuponabort=0
device.name1=cepheus
device.name2=
device.name3=
device.name4=
device.name5=
supported.versions=16
supported.patchlevels=
supported.vendorpatchlevels=
'; } # end properties


### AnyKernel install
## boot files attributes
boot_attributes() {
  set_perm_recursive 0 0 755 644 $RAMDISK/*;
  set_perm_recursive 0 0 750 750 $RAMDISK/init* $RAMDISK/sbin;
} # end attributes

# Xiaomi Cepheus is an A/B device.
# Let AnyKernel3 detect the active boot partition rather than hard-coding
# a platform-specific /dev/block path.
BLOCK=auto;
IS_SLOT_DEVICE=auto;
RAMDISK_COMPRESSION=auto;
PATCH_VBMETA_FLAG=auto;

# Do not disable Magisk preservation; AnyKernel3 will retain compatible
# boot image modifications when repacking the boot image.

# import functions/variables and setup patching - see for reference (DO NOT REMOVE)
. tools/ak3-core.sh;

# Boot installation.
dump_boot;

# No ramdisk modifications are required for the current Cepheus kernel.
# The kernel image generated by the kernel tree is Image.gz-dtb.
write_boot;
## end boot install
